### ISSUE TITLE
[PARENT ISSUE]: Finish creating all API endpoints

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/URL_Shortner_Discord_Session#1]
- [x] `POST /users/` ⚠️
- [ ] `POST /users/login` ⚠️
- [ ] `GET /users/login`
- [ ] `GET /users/login/callback`
- [ ] `POST /urls/` 🔐	#2 
- [ ] `GET /urls` 🔐 📄
- [ ] `GET /urls/{shortCode}` 🔐👮🧑
- [ ] `PATCH /urls/{shortCode}` 🔐👮🧑
- [ ] `GET /{shortCode}` 
- [ ] `GET /users/me` 🔐
- [ ] `PATCH /users/me`
