### ISSUE TITLE
[PARENT ISSUE]: Infra setup and CI/CD tasks

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/URL_Shortner_Discord_Session#3]
- [ ] Create a docker setup for the project
- [ ] Create a Heroku configuration (1-click deploy) for the project 
- [ ] Run a test on all API endpoints for Github PRs 
- [ ] Have a dev setup (prefer Heroku) always running latest `main` branch codebase
